/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objects.BaseClasses.*;

import javax.swing.*;
import javax.swing.table.*;
import java.io.*;
import java.util.*;

/**
 *
 * @author tianye
 */
public final class AccountsPage extends javax.swing.JFrame {
    
    DefaultTableModel tableModel;
    ArrayList<Account> accounts;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountsPage.class.getName());

    /**
     * Creates new form Overview
     */
    public AccountsPage() {
        initComponents();
        
        tableModel = (DefaultTableModel) tbl_accounts.getModel();
        accounts = new ArrayList<>();
        
        populateArrayList();
        for (Account a : accounts) {
            Object[] rowData = {a.getAccountName(), a.getBalance()};
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_accounts = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_accounts = new javax.swing.JTable();
        btn_addAccount = new javax.swing.JButton();
        btn_editAccount = new javax.swing.JButton();
        btn_deleteAccount = new javax.swing.JButton();
        btn_deleteAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setFocusable(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.setFocusable(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.setFocusable(false);
        btn_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_accounts.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_accounts.setText("Accounts");
        btn_accounts.setContentAreaFilled(false);
        btn_accounts.setEnabled(false);
        btn_accounts.setFocusable(false);
        jPanel1.add(btn_accounts);
        btn_accounts.setBounds(10, 260, 150, 40);

        btn_exit.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setContentAreaFilled(false);
        btn_exit.setFocusable(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("MANAGE ACCOUNTS");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 240, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(260, 40, 320, 20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tbl_accounts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_accounts.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        tbl_accounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Name", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_accounts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tbl_accounts);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 390, 280);

        btn_addAccount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_addAccount.setText("Add");
        btn_addAccount.setContentAreaFilled(false);
        btn_addAccount.setFocusPainted(false);
        btn_addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btn_addAccount);
        btn_addAccount.setBounds(460, 100, 120, 30);

        btn_editAccount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_editAccount.setText("Edit");
        btn_editAccount.setContentAreaFilled(false);
        btn_editAccount.setFocusPainted(false);
        btn_editAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editAccount);
        btn_editAccount.setBounds(460, 180, 120, 30);

        btn_deleteAccount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_deleteAccount.setText("Delete");
        btn_deleteAccount.setContentAreaFilled(false);
        btn_deleteAccount.setFocusPainted(false);
        btn_deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btn_deleteAccount);
        btn_deleteAccount.setBounds(460, 140, 120, 30);

        btn_deleteAll.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_deleteAll.setText("Clear");
        btn_deleteAll.setContentAreaFilled(false);
        btn_deleteAll.setFocusPainted(false);
        btn_deleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAllActionPerformed(evt);
            }
        });
        jPanel2.add(btn_deleteAll);
        btn_deleteAll.setBounds(460, 350, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardPage().setVisible(true);
        saveAccountsToFile();
        
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new TransactPage_InEx().setVisible(true);
        saveAccountsToFile();
        
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageActionPerformed
        new ManageTransactionsPage().setVisible(true);
        saveAccountsToFile();
        
        this.dispose();
    }//GEN-LAST:event_btn_manageActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        saveAccountsToFile();
        
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addAccountActionPerformed
        new AddAccountPopup(this, tableModel, accounts).setVisible(true);
    }//GEN-LAST:event_btn_addAccountActionPerformed

    private void btn_deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAccountActionPerformed
        if(tbl_accounts.getSelectedRow() != -1) {
            int retVal = JOptionPane.showConfirmDialog(null, 
                "Do you want to DELETE this account?", 
                "Delete Account", JOptionPane.YES_NO_OPTION);
        
            if (retVal == JOptionPane.YES_OPTION) {
                accounts.remove(tbl_accounts.getSelectedRow());
                tableModel.removeRow(tbl_accounts.getSelectedRow());
                
                saveAccountsToFile();
            }
        }
    }//GEN-LAST:event_btn_deleteAccountActionPerformed

    private void btn_editAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editAccountActionPerformed
        if(tbl_accounts.getSelectedRow() != -1) {
            Account selectedAccount = accounts.get(tbl_accounts.getSelectedRow());

            new EditAccountPopup(this, tableModel, accounts, selectedAccount, tbl_accounts.getSelectedRow()).setVisible(true);
        }
    }//GEN-LAST:event_btn_editAccountActionPerformed

    private void btn_deleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAllActionPerformed
        accounts.clear();
        saveAccountsToFile();

        new AccountsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_deleteAllActionPerformed

    
    public void saveAccountsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Accounts.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < accounts.size(); i++) {
                outputFile.writeObject(accounts.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void populateArrayList() {
        try {
            FileInputStream file = new FileInputStream("Accounts.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {                
                try {
                    accounts.add((Account) inputFile.readObject());
                } 
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (IOException | ClassNotFoundException f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccountsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accounts;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addAccount;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_deleteAccount;
    private javax.swing.JButton btn_deleteAll;
    private javax.swing.JButton btn_editAccount;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_manage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTable tbl_accounts;
    // End of variables declaration//GEN-END:variables
}
