/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objects.BaseClasses.*;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author tianye
 */
public class AddAccountPopup extends javax.swing.JFrame {
    
    static DefaultTableModel tableModel;
    static ArrayList<Account> accArray;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddAccountPopup.class.getName());

    /**
     * Creates new form AddAccountPopup
     * @param tableModel
     */
    public AddAccountPopup(DefaultTableModel tableModel, ArrayList<Account> accArray) {
        initComponents();
        
        AddAccountPopup.tableModel = tableModel;
        AddAccountPopup.accArray = accArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_balance = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        tf_balance = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("ADD ACCOUNT");
        jPanel1.add(lbl_title1);
        lbl_title1.setBounds(30, 10, 160, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(200, 30, 170, 10);

        lbl_balance.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_balance.setText("BALANCE");
        jPanel1.add(lbl_balance);
        lbl_balance.setBounds(30, 120, 110, 30);

        lbl_name.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_name.setText("ACCOUNT NAME");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(30, 60, 110, 30);

        tf_balance.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_balance);
        tf_balance.setBounds(30, 150, 340, 30);

        tf_name.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_name);
        tf_name.setBounds(30, 90, 340, 30);

        btn_add.setText("ADD");
        btn_add.setContentAreaFilled(false);
        btn_add.setFocusPainted(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(160, 200, 100, 30);

        btn_cancel.setText("CANCEL");
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.setFocusPainted(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(270, 200, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, -1, 400, 270);

        setSize(new java.awt.Dimension(410, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (tf_name.getText().isEmpty() || tf_balance.getText().isEmpty()) {
            return;
        }
        
        try {
            String name = tf_name.getText().trim();
            double balance = Double.parseDouble(tf_balance.getText());
            
            for (Account a : accArray) {
                if (a.getAccountName().equals(name)) {
                    JOptionPane.showMessageDialog(null, "[ERR] Cannot add account with same names.");
                    return;
                }
            }
            
            Object[] rowData = {name, balance};
            tableModel.addRow(rowData);
            accArray.add(new Account(name, balance));
            
            this.dispose();
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "[ERR] Cannot parse balance. Please enter a valid number.");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddAccountPopup(tableModel, accArray).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTextField tf_balance;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
