package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tianye
 */
public class DashboardPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardPage.class.getName());

    /**
     * Creates new form DashboardPage
     */
    public DashboardPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_overview = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_networth = new javax.swing.JLabel();
        lbl_income = new javax.swing.JLabel();
        lbl_expense = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transactions = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setEnabled(false);
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_overview.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_overview.setText("Overview");
        btn_overview.setContentAreaFilled(false);
        btn_overview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_overviewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_overview);
        btn_overview.setBounds(10, 260, 150, 40);

        btn_logout.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_logout.setText("Log Out ...");
        btn_logout.setContentAreaFilled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("DASHBOARD");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 130, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(170, 40, 410, 20);

        lbl_networth.setFont(new java.awt.Font("Adwaita Mono", 0, 24)); // NOI18N
        lbl_networth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_networth.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "NET WORTH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_networth);
        lbl_networth.setBounds(30, 80, 170, 100);

        lbl_income.setFont(new java.awt.Font("Adwaita Mono", 0, 24)); // NOI18N
        lbl_income.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_income.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL INCOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_income);
        lbl_income.setBounds(220, 80, 170, 100);

        lbl_expense.setFont(new java.awt.Font("Adwaita Mono", 0, 24)); // NOI18N
        lbl_expense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_expense.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL EXPENSE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_expense);
        lbl_expense.setBounds(410, 80, 170, 100);

        lbl_title2.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_title2.setText("RECENT TRANSACTIONS");
        jPanel2.add(lbl_title2);
        lbl_title2.setBounds(30, 200, 550, 40);

        tbl_transactions.setAutoCreateRowSorter(true);
        tbl_transactions.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        tbl_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Type", "Description", "Account"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_transactions.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_transactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_transactions);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 550, 220);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new NewTransactionPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageActionPerformed
        new ManageTransactionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manageActionPerformed

    private void btn_overviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_overviewActionPerformed
        new TransactionsOverviewPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_overviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manage;
    private javax.swing.JButton btn_overview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_expense;
    private javax.swing.JLabel lbl_income;
    private javax.swing.JLabel lbl_networth;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JTable tbl_transactions;
    // End of variables declaration//GEN-END:variables
}
