package GUI;

import Objects.BaseClasses.*;
import Objects.Transactions.*;

import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tianye
 */
public final class DashboardPage extends javax.swing.JFrame {
        
    DefaultTableModel tableModel;
    ArrayList<Account> accounts;
    ArrayList<Transaction> transactions;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardPage.class.getName());

    /**
     * Creates new form DashboardPage
     */
    public DashboardPage() {
        initComponents();
        
        tableModel = (DefaultTableModel) tbl_transactions.getModel();
        
        accounts = new ArrayList<>();
        transactions = new ArrayList<>();
        populateArrayList();
        
        double totIncome = 0;
        double totExpense = 0;
        double totBalance = 0;
        double netIncome;
    
        for (Transaction t : transactions) {
            String date = "";
            String type = "";
            String account = "";
            
            if (t instanceof ExpenseTransaction) {
                type = "expense";
                account = t.getAccount().getFirst().getAccountName();
                
                totExpense += t.getAmount();
            }
            else if (t instanceof IncomeTransaction) {
                type = "income";
                account = t.getAccount().getFirst().getAccountName();
                
                totIncome += t.getAmount();
            }
            else if (t instanceof TransferTransaction) {
                type = "transfer";
                
                String src = t.getAccount().getFirst().getAccountName();
                String dst = t.getAccount().getLast().getAccountName();
                
                account = String.format("%s ---> %s", src, dst);
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("EEE, yyyy-MM-dd");
            date = sdf.format(t.getDate());
            
            Object[] rowData = {t.getTransactionID(), date, t.getAmount(), type, t.getDescription(), account};
            tableModel.addRow(rowData);
        }
        
        for (Account a : accounts) {
            totBalance += a.getBalance();
        }
        
        netIncome = (totIncome - totExpense);
        
        lbl_balance.setText(String.valueOf(totBalance));
        lbl_netIncome.setText(String.valueOf(netIncome));
        lbl_income.setText(String.valueOf(totIncome));
        lbl_expense.setText(String.valueOf(totExpense));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_accounts = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_netIncome = new javax.swing.JLabel();
        lbl_income = new javax.swing.JLabel();
        lbl_expense = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transactions = new javax.swing.JTable();
        lbl_balance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setEnabled(false);
        btn_dashboard.setFocusPainted(false);
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.setFocusPainted(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.setFocusPainted(false);
        btn_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_accounts.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_accounts.setText("Accounts");
        btn_accounts.setContentAreaFilled(false);
        btn_accounts.setFocusPainted(false);
        btn_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accountsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accounts);
        btn_accounts.setBounds(10, 260, 150, 40);

        btn_exit.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setContentAreaFilled(false);
        btn_exit.setFocusPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("DASHBOARD");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 130, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(170, 40, 410, 20);

        lbl_netIncome.setFont(new java.awt.Font("Adwaita Mono", 0, 24)); // NOI18N
        lbl_netIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_netIncome.setText("0");
        lbl_netIncome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "NET INCOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_netIncome);
        lbl_netIncome.setBounds(410, 80, 170, 100);

        lbl_income.setFont(new java.awt.Font("Adwaita Mono", 0, 18)); // NOI18N
        lbl_income.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_income.setText("0");
        lbl_income.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL INCOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_income);
        lbl_income.setBounds(220, 130, 170, 50);

        lbl_expense.setFont(new java.awt.Font("Adwaita Mono", 0, 18)); // NOI18N
        lbl_expense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_expense.setText("0");
        lbl_expense.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL EXPENSE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_expense);
        lbl_expense.setBounds(220, 80, 170, 50);

        lbl_title2.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_title2.setText("RECENT TRANSACTIONS");
        jPanel2.add(lbl_title2);
        lbl_title2.setBounds(30, 200, 550, 40);

        tbl_transactions.setAutoCreateRowSorter(true);
        tbl_transactions.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        tbl_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Type", "Description", "Account"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_transactions.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_transactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_transactions);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 550, 220);

        lbl_balance.setFont(new java.awt.Font("Adwaita Mono", 0, 24)); // NOI18N
        lbl_balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_balance.setText("0");
        lbl_balance.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL BALANCE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adwaita Mono", 1, 13))); // NOI18N
        jPanel2.add(lbl_balance);
        lbl_balance.setBounds(30, 80, 170, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new TransactPage_InEx().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageActionPerformed
        new ManageTransactionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manageActionPerformed

    private void btn_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accountsActionPerformed
        new AccountsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_accountsActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    
    public void saveAccountsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Accounts.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < accounts.size(); i++) {
                outputFile.writeObject(accounts.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void saveTransactionsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Transactions.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < transactions.size(); i++) {
                outputFile.writeObject(transactions.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void populateArrayList() {
        try {
            FileInputStream file = new FileInputStream("Accounts.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {                
                try {
                    accounts.add((Account) inputFile.readObject());
                } 
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (IOException | ClassNotFoundException f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            FileInputStream file2 = new FileInputStream("Transactions.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {                
                try {
                    transactions.add((Transaction) inputFile2.readObject());
                } 
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (IOException | ClassNotFoundException f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile2.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accounts;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_manage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_expense;
    private javax.swing.JLabel lbl_income;
    private javax.swing.JLabel lbl_netIncome;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JTable tbl_transactions;
    // End of variables declaration//GEN-END:variables
}
