/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objects.BaseClasses.*;
import Objects.Transactions.*;

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author tianye
 */
public final class EditTransactionPopup_InEx extends javax.swing.JFrame {
    
    static ManageTransactionsPage parent;
    
    DefaultListModel<String> listModel;
    static DefaultTableModel tableModel;
    static ArrayList<Transaction> trnsArray;
    static ArrayList<Account> accArray;
    static Transaction selectedTransaction;
    static int selectedRow;
    static int typeInd;
    
    String transactionType;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditTransactionPopup_InEx.class.getName());

    /**
     * Creates new form EditTransactionPopup
     * 
     * @param parent
     * @param tableModel
     * @param trnsArray
     * @param accArray
     * @param selectedTransaction
     * @param selectedRow
     * @param typeInd
     */
    public EditTransactionPopup_InEx(ManageTransactionsPage parent, DefaultTableModel tableModel, ArrayList<Transaction> trnsArray, ArrayList<Account> accArray, Transaction selectedTransaction, int selectedRow, int typeInd) {
        initComponents();
        
        EditTransactionPopup_InEx.parent = parent;
        parent.setEnabled(false);
        
        list_account.setModel(new DefaultListModel<>());
        listModel = (DefaultListModel) list_account.getModel();
        
        EditTransactionPopup_InEx.tableModel = tableModel;
        EditTransactionPopup_InEx.trnsArray = trnsArray;
        EditTransactionPopup_InEx.accArray = accArray;
        EditTransactionPopup_InEx.selectedTransaction = selectedTransaction;
        EditTransactionPopup_InEx.selectedRow = selectedRow;
        EditTransactionPopup_InEx.typeInd = typeInd;
        
        tf_amount.setText(String.valueOf(selectedTransaction.getAmount()));
        cmb_type.setSelectedIndex(typeInd);
        tf_description.setText(selectedTransaction.getDescription());
        dc_date.setDate(selectedTransaction.getDate());
        
        switch (cmb_type.getSelectedIndex()) {
            case 0 -> transactionType = "expense";
            case 1 -> transactionType = "income";
            default -> {
            }
        }
        
        for (Account a : accArray) {
            listModel.addElement(a.getAccountName());
        }
        for(int i=0; i < listModel.getSize(); i++){
            String s =  listModel.getElementAt(i);
            
            if (s.equals(selectedTransaction.getAccount().getFirst().getAccountName())) {
                list_account.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_title1 = new javax.swing.JLabel();
        lbl_account = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_account = new javax.swing.JList<>();
        lbl_amount = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        tf_description = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        lbl_type = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        btn_confirm = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Edit Transaction");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(200, 30, 200, 10);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("EDIT ACCOUNT");
        jPanel1.add(lbl_title1);
        lbl_title1.setBounds(20, 10, 170, 40);

        lbl_account.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_account.setText("ACCOUNT");
        jPanel1.add(lbl_account);
        lbl_account.setBounds(20, 220, 100, 30);

        list_account.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        list_account.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(list_account);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 250, 100, 120);

        lbl_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_amount.setText("AMOUNT");
        jPanel1.add(lbl_amount);
        lbl_amount.setBounds(20, 70, 110, 30);

        tf_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_amount);
        tf_amount.setBounds(20, 100, 240, 30);

        lbl_description.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_description.setText("DESCRIPTION");
        jPanel1.add(lbl_description);
        lbl_description.setBounds(20, 140, 390, 30);

        tf_description.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_description);
        tf_description.setBounds(20, 170, 240, 30);

        lbl_date.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_date.setText("DATE");
        jPanel1.add(lbl_date);
        lbl_date.setBounds(290, 140, 110, 30);
        jPanel1.add(dc_date);
        dc_date.setBounds(290, 170, 110, 30);

        lbl_type.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_type.setText("TYPE");
        jPanel1.add(lbl_type);
        lbl_type.setBounds(290, 70, 110, 30);

        cmb_type.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "expense", "income", "transfer" }));
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_type);
        cmb_type.setBounds(290, 100, 110, 30);

        btn_confirm.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_confirm.setText("CONFIRM");
        btn_confirm.setContentAreaFilled(false);
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(btn_confirm);
        btn_confirm.setBounds(290, 300, 110, 30);

        btn_cancel.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.setFocusPainted(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(290, 340, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 480);

        setSize(new java.awt.Dimension(430, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        switch (cmb_type.getSelectedIndex()) {
            case 0 -> {
                // Expense
                transactionType = "expense";
            }
            case 1 -> {
                // Income
                transactionType = "income";
            }
            case 2 -> {
                new EditTransactionPopup_Tran(parent, tableModel, trnsArray, accArray, selectedTransaction, selectedRow).setVisible(true);
                this.dispose();
            }
            default -> throw new AssertionError();
        }

    }//GEN-LAST:event_cmb_typeActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        if (list_account.isSelectionEmpty()|| tf_amount.getText().isEmpty() || dc_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "[ERR] Empty fields found.");
            return;
        }
        
        try {
            int t_id = selectedTransaction.getTransactionID();
            Date date = dc_date.getDate();
            double amnt = Double.parseDouble(tf_amount.getText());
            String desc = tf_description.getText();

            Account acc = null;
            int accInd = 0;
            for (Account a : accArray) {
                if (a.getAccountName().equals(list_account.getSelectedValue())) {
                    acc = a;
                    accInd = accArray.indexOf(a);
                    break;
                }
            }

            Transaction oldTransaction = selectedTransaction;
            oldTransaction.undoTransaction();
            
            acc = oldTransaction.getAccount().getFirst();
            accArray.set(accInd, acc);

            Transaction newTransaction = null;
            if (transactionType.equals("expense")) {
                if (amnt > acc.getBalance() || amnt <= 0) {
                    JOptionPane.showMessageDialog(null, "[ERR] Invalid amount.");
                    return;
                }
                newTransaction = new ExpenseTransaction(t_id, date, amnt, desc, acc);
            }
            else if (transactionType.equals("income")) {
                if (amnt <= 0) {
                    JOptionPane.showMessageDialog(null, "[ERR] Invalid amount.");
                    return;
                }
                newTransaction = new IncomeTransaction(t_id, date, amnt, desc, acc);
            }

            newTransaction.confirmTransaction();
            
            for (int i = 0; i < trnsArray.size(); i++) {
                if (trnsArray.get(i).getTransactionID() == t_id) {
                    trnsArray.set(i, newTransaction);
                    break;
                }
            }
            
            acc = newTransaction.getAccount().getFirst();
            accArray.set(accInd, acc);

            JOptionPane.showMessageDialog(null, "Transaction Revised.");
            saveAccountsToFile();
            saveTransactionsToFile();
            
            parent.dispose();
            new ManageTransactionsPage().setVisible(true);
            
            this.dispose();
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "[ERR] Invalid amount.");
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        parent.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    
    public void saveAccountsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Accounts.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < accArray.size(); i++) {
                outputFile.writeObject(accArray.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void saveTransactionsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Transactions.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);

            for (int i = 0; i < trnsArray.size(); i++) {
                outputFile.writeObject(trnsArray.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditTransactionPopup_InEx(parent, tableModel, trnsArray, accArray, selectedTransaction, selectedRow, typeInd).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JComboBox<String> cmb_type;
    private com.toedter.calendar.JDateChooser dc_date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JList<String> list_account;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_description;
    // End of variables declaration//GEN-END:variables
}
