/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objects.BaseClasses.*;
import Objects.Transactions.*;

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author tianye
 */
public final class EditTransactionPopup_Tran extends javax.swing.JFrame {
    
    static ManageTransactionsPage parent;
    
    DefaultListModel<String> listModelSrc;
    DefaultListModel<String> listModelDst;
    
    static DefaultTableModel tableModel;
    static ArrayList<Transaction> trnsArray;
    static ArrayList<Account> accArray;
    static Transaction selectedTransaction;
    static int selectedRow;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditTransactionPopup_Tran.class.getName());

    /**
     * Creates new form EditTransactionPopup
     * 
     * @param parent
     * @param tableModel
     * @param trnsArray
     * @param accArray
     * @param selectedTransaction
     * @param selectedRow
     */
    public EditTransactionPopup_Tran(ManageTransactionsPage parent, DefaultTableModel tableModel, ArrayList<Transaction> trnsArray, ArrayList<Account> accArray, Transaction selectedTransaction, int selectedRow) {
        initComponents();
        
        EditTransactionPopup_Tran.parent = parent;
        parent.setEnabled(false);
        
        list_source.setModel(new DefaultListModel<>());
        listModelSrc = (DefaultListModel) list_source.getModel();
        list_destination.setModel(new DefaultListModel<>());
        listModelDst = (DefaultListModel) list_destination.getModel();
        
        EditTransactionPopup_Tran.tableModel = tableModel;
        EditTransactionPopup_Tran.trnsArray = trnsArray;
        EditTransactionPopup_Tran.accArray = accArray;
        EditTransactionPopup_Tran.selectedTransaction = selectedTransaction;
        EditTransactionPopup_Tran.selectedRow = selectedRow;
        
        tf_amount.setText(String.valueOf(selectedTransaction.getAmount()));

        tf_description.setText(selectedTransaction.getDescription());
        dc_date.setDate(selectedTransaction.getDate());
        
        
        for (Account a : accArray) {
            listModelSrc.addElement(a.getAccountName());
            listModelDst.addElement(a.getAccountName());
        }
        for(int i=0; i < listModelSrc.getSize(); i++){
            String s =  listModelSrc.getElementAt(i);
            
            if (s.equals(selectedTransaction.getAccount().getFirst().getAccountName())) {
                list_source.setSelectedIndex(i);
                break;
            }
        }
        for(int i=0; i < listModelDst.getSize(); i++){
            String s =  listModelDst.getElementAt(i);
            
            if (s.equals(selectedTransaction.getAccount().getLast().getAccountName())) {
                list_destination.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_title1 = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        tf_description = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        lbl_type = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        btn_confirm = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_destination = new javax.swing.JList<>();
        lbl_account2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_source = new javax.swing.JList<>();
        lbl_account1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Edit Transaction");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(200, 30, 200, 10);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("EDIT ACCOUNT");
        jPanel1.add(lbl_title1);
        lbl_title1.setBounds(20, 10, 170, 40);

        lbl_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_amount.setText("AMOUNT");
        jPanel1.add(lbl_amount);
        lbl_amount.setBounds(20, 70, 110, 30);

        tf_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_amount);
        tf_amount.setBounds(20, 100, 240, 30);

        lbl_description.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_description.setText("DESCRIPTION");
        jPanel1.add(lbl_description);
        lbl_description.setBounds(20, 140, 390, 30);

        tf_description.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel1.add(tf_description);
        tf_description.setBounds(20, 170, 240, 30);

        lbl_date.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_date.setText("DATE");
        jPanel1.add(lbl_date);
        lbl_date.setBounds(290, 140, 110, 30);
        jPanel1.add(dc_date);
        dc_date.setBounds(290, 170, 110, 30);

        lbl_type.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_type.setText("TYPE");
        jPanel1.add(lbl_type);
        lbl_type.setBounds(290, 70, 110, 30);

        cmb_type.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "expense", "income", "transfer" }));
        cmb_type.setSelectedIndex(2);
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_type);
        cmb_type.setBounds(290, 100, 110, 30);

        btn_confirm.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_confirm.setText("CONFIRM");
        btn_confirm.setContentAreaFilled(false);
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(btn_confirm);
        btn_confirm.setBounds(290, 300, 110, 30);

        btn_cancel.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.setFocusPainted(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(290, 340, 110, 30);

        list_destination.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        list_destination.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(list_destination);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(150, 250, 100, 120);

        lbl_account2.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        lbl_account2.setText("TO ACCOUNT");
        jPanel1.add(lbl_account2);
        lbl_account2.setBounds(150, 220, 100, 30);

        list_source.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        list_source.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(list_source);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 100, 120);

        lbl_account1.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        lbl_account1.setText("FROM ACCOUNT");
        jPanel1.add(lbl_account1);
        lbl_account1.setBounds(20, 220, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 480);

        setSize(new java.awt.Dimension(430, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        switch (cmb_type.getSelectedIndex()) {
            case 0 -> {
                // Expense
                new EditTransactionPopup_InEx(parent, tableModel, trnsArray, accArray, selectedTransaction, selectedRow, 0).setVisible(true);
                this.dispose();
            }
            case 1 -> {
                // Income
                new EditTransactionPopup_InEx(parent, tableModel, trnsArray, accArray, selectedTransaction, selectedRow, 1).setVisible(true);
                this.dispose();
            }
            case 2 -> {
                // Transfer
            }
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        if (list_source.isSelectionEmpty()|| list_destination.isSelectionEmpty()|| tf_amount.getText().isEmpty() || dc_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "[ERR] Empty fields found.");
            return;
        }
        if (list_source.getSelectedValue().equals(list_destination.getSelectedValue())) {
            JOptionPane.showMessageDialog(null, "[ERR] Source and Destination cannot be the same.");
            return;
        }
        
        try {
            int t_id = selectedTransaction.getTransactionID();
            Date date = dc_date.getDate();
            double amnt = Double.parseDouble(tf_amount.getText());
            String desc = tf_description.getText();

            Account accSrc = null;
            int accIndSrc = 0;
            for (Account a : accArray) {
                if (a.getAccountName().equals(list_source.getSelectedValue())) {
                    accSrc = a;
                    accIndSrc = accArray.indexOf(a);
                    break;
                }
            }
            Account accDst = null;
            int accIndDst = 0;
            for (Account a : accArray) {
                if (a.getAccountName().equals(list_destination.getSelectedValue())) {
                    accDst = a;
                    accIndDst = accArray.indexOf(a);
                    break;
                }
            }
            
            if (accSrc == null || accDst == null) {
                JOptionPane.showMessageDialog(null, "[ERR] Could not find selected account.");
                return;
            }

            selectedTransaction.undoTransaction();
            for (Account a : accArray) {
                if (a.getAccountName().equals(selectedTransaction.getAccount().getFirst().getAccountName())) {
                    a.deposit(selectedTransaction.getAmount());
                }
                else if (a.getAccountName().equals(selectedTransaction.getAccount().getLast().getAccountName())) {
                    a.withdraw(selectedTransaction.getAmount());
                }
            }

            if (amnt <= 0) {
                JOptionPane.showMessageDialog(null,"[ERR] Invalid amount.");
                return;
            }

            if (amnt > accSrc.getBalance()) {
                JOptionPane.showMessageDialog(null, "[ERR] Insufficient balance.");
                return;
            }

            Transaction newTransaction = new TransferTransaction(t_id, date, amnt, desc, accSrc, accDst);
            newTransaction.confirmTransaction();

            for (int i = 0; i < trnsArray.size(); i++) {

                if (trnsArray.get(i).getTransactionID() == t_id) {
                    trnsArray.set(i, newTransaction);
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "Transaction Revised.");
            saveAccountsToFile();
            saveTransactionsToFile();
            
            parent.dispose();
            new ManageTransactionsPage().setVisible(true);
            
            this.dispose();
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "[ERR] Invalid amount.");
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        parent.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    
    public void saveAccountsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Accounts.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < accArray.size(); i++) {
                outputFile.writeObject(accArray.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void saveTransactionsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Transactions.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < trnsArray.size(); i++) {
                outputFile.writeObject(trnsArray.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditTransactionPopup_Tran(parent, tableModel, trnsArray, accArray, selectedTransaction, selectedRow).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JComboBox<String> cmb_type;
    private com.toedter.calendar.JDateChooser dc_date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_account1;
    private javax.swing.JLabel lbl_account2;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JList<String> list_destination;
    private javax.swing.JList<String> list_source;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_description;
    // End of variables declaration//GEN-END:variables
}
