/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianye
 */
public class ManageTransactionsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageTransactionsPage.class.getName());

    /**
     * Creates new form ManageTransactions
     */
    public ManageTransactionsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_overview = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf_search = new javax.swing.JTextField();
        cmb_filter = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transactions = new javax.swing.JTable();
        btn_editRow = new javax.swing.JButton();
        btn_deleteRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.setEnabled(false);
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_overview.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_overview.setText("Overview");
        btn_overview.setContentAreaFilled(false);
        btn_overview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_overviewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_overview);
        btn_overview.setBounds(10, 260, 150, 40);

        btn_logout.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_logout.setText("Log Out ...");
        btn_logout.setContentAreaFilled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("MANAGE TRANSACTIONS");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 270, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(310, 40, 270, 20);

        tf_search.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel2.add(tf_search);
        tf_search.setBounds(30, 80, 220, 30);

        cmb_filter.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        cmb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Amount", "Type", "Description", "Account" }));
        jPanel2.add(cmb_filter);
        cmb_filter.setBounds(260, 80, 110, 30);

        btn_search.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btn_search.setText("Search");
        btn_search.setContentAreaFilled(false);
        jPanel2.add(btn_search);
        btn_search.setBounds(467, 80, 110, 30);

        tbl_transactions.setAutoCreateRowSorter(true);
        tbl_transactions.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        tbl_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Type", "Description", "Account"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_transactions.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_transactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_transactions);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 550, 290);

        btn_editRow.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_editRow.setText("Edit");
        btn_editRow.setContentAreaFilled(false);
        btn_editRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editRowActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editRow);
        btn_editRow.setBounds(350, 430, 110, 30);

        btn_deleteRow.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_deleteRow.setText("Delete");
        btn_deleteRow.setContentAreaFilled(false);
        btn_deleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteRowActionPerformed(evt);
            }
        });
        jPanel2.add(btn_deleteRow);
        btn_deleteRow.setBounds(470, 430, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new NewTransactionPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_overviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_overviewActionPerformed
        new TransactionsOverviewPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_overviewActionPerformed

    private void btn_deleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteRowActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tbl_transactions.getModel();
        
        if(tbl_transactions.getSelectedRow() != -1) 
            {
                tableModel.removeRow(tbl_transactions.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Record deleted!");
            }
    }//GEN-LAST:event_btn_deleteRowActionPerformed

    private void btn_editRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageTransactionsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_deleteRow;
    private javax.swing.JButton btn_editRow;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manage;
    private javax.swing.JButton btn_overview;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTable tbl_transactions;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
