/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objects.BaseClasses.*;
import Objects.Transactions.*;

import java.io.*;
import java.text.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import java.util.regex.*;
import javax.swing.event.*;

/**
 *
 * @author tianye
 */
public final class ManageTransactionsPage extends javax.swing.JFrame {
    
    DefaultTableModel tableModel;
    ArrayList<Account> accounts;
    ArrayList<Transaction> transactions;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageTransactionsPage.class.getName());

    /**
     * Creates new form ManageTransactions
     */
    public ManageTransactionsPage() {
        initComponents();
        
        tableModel = (DefaultTableModel) tbl_transactions.getModel();
        
        accounts = new ArrayList<>();
        transactions = new ArrayList<>();
        populateArrayList();
        
        for (Transaction t : transactions) {
            String date = "";
            String type = "";
            String account = "";
            
            if (t instanceof ExpenseTransaction) {
                type = "expense";
                account = t.getAccount().getFirst().getAccountName();
            }
            else if (t instanceof IncomeTransaction) {
                type = "income";
                account = t.getAccount().getFirst().getAccountName();
            }
            else if (t instanceof TransferTransaction) {
                type = "transfer";
                
                String src = t.getAccount().getFirst().getAccountName();
                String dst = t.getAccount().getLast().getAccountName();
                
                account = String.format("%s ---> %s", src, dst);
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("EEE, yyyy-MM-dd");
            date = sdf.format(t.getDate());
            
            Object[] rowData = {t.getTransactionID(), date, t.getAmount(), type, t.getDescription(), account};
            tableModel.addRow(rowData);
        }
        
        addFilter(tbl_transactions, tf_search, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_accounts = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf_search = new javax.swing.JTextField();
        cmb_filter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transactions = new javax.swing.JTable();
        btn_deleteAll = new javax.swing.JButton();
        btn_deleteRow = new javax.swing.JButton();
        btn_editRow = new javax.swing.JButton();
        btn_clearSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setFocusPainted(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.setFocusPainted(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.setEnabled(false);
        btn_manage.setFocusPainted(false);
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_accounts.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_accounts.setText("Accounts");
        btn_accounts.setContentAreaFilled(false);
        btn_accounts.setFocusPainted(false);
        btn_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accountsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accounts);
        btn_accounts.setBounds(10, 260, 150, 40);

        btn_exit.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setContentAreaFilled(false);
        btn_exit.setFocusPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("MANAGE TRANSACTIONS");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 270, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(310, 40, 270, 20);

        tf_search.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel2.add(tf_search);
        tf_search.setBounds(30, 80, 240, 30);

        cmb_filter.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        cmb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Amount", "Type", "Description", "Account" }));
        cmb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_filterActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_filter);
        cmb_filter.setBounds(280, 80, 110, 30);

        tbl_transactions.setAutoCreateRowSorter(true);
        tbl_transactions.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        tbl_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Type", "Description", "Account"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_transactions.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_transactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_transactions);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 550, 270);

        btn_deleteAll.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_deleteAll.setText("Clear");
        btn_deleteAll.setContentAreaFilled(false);
        btn_deleteAll.setFocusPainted(false);
        btn_deleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAllActionPerformed(evt);
            }
        });
        jPanel2.add(btn_deleteAll);
        btn_deleteAll.setBounds(30, 420, 110, 30);

        btn_deleteRow.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_deleteRow.setText("Delete");
        btn_deleteRow.setContentAreaFilled(false);
        btn_deleteRow.setFocusPainted(false);
        btn_deleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteRowActionPerformed(evt);
            }
        });
        jPanel2.add(btn_deleteRow);
        btn_deleteRow.setBounds(470, 420, 110, 30);

        btn_editRow.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_editRow.setText("Edit");
        btn_editRow.setContentAreaFilled(false);
        btn_editRow.setFocusPainted(false);
        btn_editRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editRowActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editRow);
        btn_editRow.setBounds(350, 420, 110, 30);

        btn_clearSearch.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_clearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list-x.png"))); // NOI18N
        btn_clearSearch.setContentAreaFilled(false);
        btn_clearSearch.setFocusPainted(false);
        btn_clearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clearSearch);
        btn_clearSearch.setBounds(550, 80, 30, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new TransactPage_InEx().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accountsActionPerformed
        new AccountsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_accountsActionPerformed

    private void btn_deleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteRowActionPerformed
        if(tbl_transactions.getSelectedRow() != -1) {
            Transaction selectedTran = transactions.get(tbl_transactions.getSelectedRow());
            
            int retVal = JOptionPane.showConfirmDialog(null, 
                "Do you want to DELETE this transaction?", 
                "Delete Transaction", JOptionPane.YES_NO_OPTION);
        
            if (retVal == JOptionPane.YES_OPTION) {
                ArrayList<Account> selectedAcc = selectedTran.getAccount();
                
                selectedTran.undoTransaction();
                if (selectedTran instanceof TransferTransaction) {
                    for (Account a : accounts) {
                        if (selectedAcc.getFirst().getAccountName().equals(a.getAccountName())) {
                            accounts.set(accounts.indexOf(a), selectedAcc.getFirst());
                        }
                        else if (selectedAcc.getLast().getAccountName().equals(a.getAccountName())) {
                            accounts.set(accounts.indexOf(a), selectedAcc.getLast());
                        }
                    }
                }
                else {
                    for (Account a : accounts) {
                        if (selectedTran instanceof ExpenseTransaction) {
                            if (selectedAcc.getFirst().getAccountName().equals(a.getAccountName())) {
                                accounts.set(accounts.indexOf(a), selectedAcc.getFirst());
                            }
                        }
                        else if (selectedTran instanceof IncomeTransaction) {
                            if (selectedAcc.getFirst().getAccountName().equals(a.getAccountName())) {
                                accounts.set(accounts.indexOf(a), selectedAcc.getFirst());
                            }
                        }
                    }
                }

                transactions.remove(tbl_transactions.getSelectedRow());
                tableModel.removeRow(tbl_transactions.getSelectedRow());
                
                saveAccountsToFile();
                saveTransactionsToFile();
            }
        }
    }//GEN-LAST:event_btn_deleteRowActionPerformed

    private void btn_editRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editRowActionPerformed
        if(tbl_transactions.getSelectedRow() != -1) {
            Transaction selectedTransaction = transactions.get((int) tbl_transactions.getValueAt(tbl_transactions.getSelectedRow(), 0));
            
            if (selectedTransaction instanceof ExpenseTransaction) {
                new EditTransactionPopup_InEx(this, tableModel, transactions, accounts, selectedTransaction, tbl_transactions.getSelectedRow(), 0).setVisible(true);
            }
            else if (selectedTransaction instanceof IncomeTransaction) {
                new EditTransactionPopup_InEx(this, tableModel, transactions, accounts, selectedTransaction, tbl_transactions.getSelectedRow(), 1).setVisible(true);
            }
            else if (selectedTransaction instanceof TransferTransaction) {
                new EditTransactionPopup_Tran(this, tableModel, transactions, accounts, selectedTransaction, tbl_transactions.getSelectedRow()).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_editRowActionPerformed

    private void btn_clearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearSearchActionPerformed
        cmb_filter.setSelectedIndex(0);
        tf_search.setText("");
    }//GEN-LAST:event_btn_clearSearchActionPerformed

    private void cmb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_filterActionPerformed
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbl_transactions.getModel());
        tbl_transactions.setRowSorter(rowSorter);
        
        int category = cmb_filter.getSelectedIndex() + 1;
        addFilter(tbl_transactions, tf_search, category);
    }//GEN-LAST:event_cmb_filterActionPerformed

    private void btn_deleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAllActionPerformed
        if (!transactions.isEmpty()) {
            int retVal = JOptionPane.showConfirmDialog(null, 
                "Do you want to DELETE ALL transactions?", 
                "Delete ALL Transactions", JOptionPane.YES_NO_OPTION);
        
            if (retVal == JOptionPane.YES_OPTION) {
                for (int i = 0; i < transactions.size(); i++) {
                    transactions.get(i).undoTransaction();
                    for (Account ta : transactions.get(i).getAccount()) {
                        for (Account a : accounts) {
                            if (ta.getAccountName().equals(a.getAccountName())) {
                                accounts.set(accounts.indexOf(a), ta);
                            }
                        }
                    }
                }
                transactions.clear();
                saveAccountsToFile();
                saveTransactionsToFile();

                new ManageTransactionsPage().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_deleteAllActionPerformed


    public static void addFilter(JTable tbl, JTextField txtSearch, int SearchColumnIndex) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        final TableRowSorter< DefaultTableModel> sorter = new TableRowSorter< DefaultTableModel>(model);
        tbl.setRowSorter(sorter);

        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                OnChange();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                OnChange();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                OnChange();
            }
            public void OnChange() {
                var txt = txtSearch.getText().toLowerCase();
                if (txt.length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    try {
                        sorter.setRowFilter(RowFilter.regexFilter("^(?i)" + txt, SearchColumnIndex));
                    } catch (PatternSyntaxException pse) {
                        System.out.println("Bad regex pattern");
                    }
                }

            }
        });
    }

    public void saveAccountsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Accounts.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < accounts.size(); i++) {
                outputFile.writeObject(accounts.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void saveTransactionsToFile() {
        try {
            FileOutputStream file = new FileOutputStream("Transactions.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < transactions.size(); i++) {
                outputFile.writeObject(transactions.get(i));
            }
            outputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public void populateArrayList() {
        try {
            FileInputStream file = new FileInputStream("Accounts.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {                
                try {
                    accounts.add((Account) inputFile.readObject());
                } 
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (IOException | ClassNotFoundException f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            FileInputStream file2 = new FileInputStream("Transactions.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {                
                try {
                    transactions.add((Transaction) inputFile2.readObject());
                } 
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (IOException | ClassNotFoundException f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile2.close();
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageTransactionsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accounts;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clearSearch;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_deleteAll;
    private javax.swing.JButton btn_deleteRow;
    private javax.swing.JButton btn_editRow;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_manage;
    private javax.swing.JComboBox<String> cmb_filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTable tbl_transactions;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
