/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author tianye
 */
public class NewTransactionPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewTransactionPage.class.getName());

    /**
     * Creates new form NewTransaction
     */
    public NewTransactionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_appName = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_manage = new javax.swing.JButton();
        btn_overview = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_date = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        lbl_type = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        tf_description = new javax.swing.JTextField();
        lbl_amount = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        btn_confirm = new javax.swing.JButton();
        lbl_amount1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_account = new javax.swing.JList<>();
        cmb_type = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_appName.setFont(new java.awt.Font("Adwaita Mono", 1, 18)); // NOI18N
        lbl_appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet-note.png"))); // NOI18N
        lbl_appName.setText("MFINANCE");
        lbl_appName.setIconTextGap(10);
        jPanel1.add(lbl_appName);
        lbl_appName.setBounds(20, 20, 130, 40);

        btn_dashboard.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard);
        btn_dashboard.setBounds(10, 90, 150, 40);

        btn_add.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_add.setText("New Record");
        btn_add.setContentAreaFilled(false);
        btn_add.setEnabled(false);
        jPanel1.add(btn_add);
        btn_add.setBounds(10, 160, 150, 40);

        btn_manage.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_manage.setText("Manage Records");
        btn_manage.setContentAreaFilled(false);
        btn_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manage);
        btn_manage.setBounds(10, 210, 150, 40);

        btn_overview.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_overview.setText("Overview");
        btn_overview.setContentAreaFilled(false);
        btn_overview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_overviewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_overview);
        btn_overview.setBounds(10, 260, 150, 40);

        btn_logout.setFont(new java.awt.Font("Adwaita Mono", 0, 12)); // NOI18N
        btn_logout.setText("Log Out ...");
        btn_logout.setContentAreaFilled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(10, 420, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 480);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        lbl_title1.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title1.setText("NEW TRANSACTION");
        jPanel2.add(lbl_title1);
        lbl_title1.setBounds(30, 20, 220, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(250, 40, 330, 20);

        lbl_date.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_date.setText("DATE");
        jPanel2.add(lbl_date);
        lbl_date.setBounds(150, 210, 150, 30);
        jPanel2.add(dc_date);
        dc_date.setBounds(150, 240, 150, 30);

        lbl_type.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_type.setText("TYPE");
        jPanel2.add(lbl_type);
        lbl_type.setBounds(420, 70, 160, 30);

        lbl_description.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_description.setText("DESCRIPTION");
        jPanel2.add(lbl_description);
        lbl_description.setBounds(150, 140, 430, 30);

        tf_description.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel2.add(tf_description);
        tf_description.setBounds(150, 170, 430, 30);

        lbl_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_amount.setText("AMOUNT");
        jPanel2.add(lbl_amount);
        lbl_amount.setBounds(150, 70, 150, 30);

        tf_amount.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        jPanel2.add(tf_amount);
        tf_amount.setBounds(150, 100, 230, 30);

        btn_confirm.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        btn_confirm.setText("CONFIRM");
        btn_confirm.setContentAreaFilled(false);
        jPanel2.add(btn_confirm);
        btn_confirm.setBounds(470, 240, 110, 30);

        lbl_amount1.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_amount1.setText("ACCOUNT");
        jPanel2.add(lbl_amount1);
        lbl_amount1.setBounds(30, 70, 100, 30);

        list_account.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        list_account.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cash", "Savings", "Debit", "Credit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_account.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(list_account);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(30, 100, 100, 170);

        cmb_type.setFont(new java.awt.Font("Adwaita Mono", 0, 13)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expense", "Income" }));
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_type);
        cmb_type.setBounds(420, 100, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 0, 610, 480);

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageActionPerformed
        new ManageTransactionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manageActionPerformed

    private void btn_overviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_overviewActionPerformed
        new TransactionsOverviewPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_overviewActionPerformed

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        switch (cmb_type.getSelectedIndex()) {
            case 0:     // Expense
                
                break;
            case 1:     // Income
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_cmb_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewTransactionPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manage;
    private javax.swing.JButton btn_overview;
    private javax.swing.JComboBox<String> cmb_type;
    private com.toedter.calendar.JDateChooser dc_date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_amount1;
    private javax.swing.JLabel lbl_appName;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JList<String> list_account;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_description;
    // End of variables declaration//GEN-END:variables
}
