package GUI.unused;

import GUI.DashboardPage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tianye
 */
public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_username = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MFinance Tracker");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl_title.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lbl_title.setText("LOG IN");
        jPanel1.add(lbl_title);
        lbl_title.setBounds(50, 20, 300, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(50, 60, 310, 20);

        lbl_username.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_username.setText("USERNAME");
        jPanel1.add(lbl_username);
        lbl_username.setBounds(50, 70, 300, 30);
        jPanel1.add(tf_username);
        tf_username.setBounds(50, 100, 310, 30);

        lbl_password.setFont(new java.awt.Font("Adwaita Mono", 0, 14)); // NOI18N
        lbl_password.setText("PASSWORD");
        jPanel1.add(lbl_password);
        lbl_password.setBounds(50, 130, 300, 30);
        jPanel1.add(pf_password);
        pf_password.setBounds(50, 160, 310, 30);

        btn_login.setText("LOG IN");
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login);
        btn_login.setBounds(220, 210, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 280);

        setSize(new java.awt.Dimension(410, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        new DashboardPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
